/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentReturnRouteImport } from './routes/payment/return'
import { Route as ApiDownloadImageRouteImport } from './routes/api/download-image'
import { Route as ApiXunhupayNotifyRouteImport } from './routes/api/xunhupay/notify'
import { Route as ApiHistoryThumbnailIdRouteImport } from './routes/api/history-thumbnail.$id'

const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment/return',
  path: '/payment/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadImageRoute = ApiDownloadImageRouteImport.update({
  id: '/api/download-image',
  path: '/api/download-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXunhupayNotifyRoute = ApiXunhupayNotifyRouteImport.update({
  id: '/api/xunhupay/notify',
  path: '/api/xunhupay/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryThumbnailIdRoute = ApiHistoryThumbnailIdRouteImport.update({
  id: '/api/history-thumbnail/$id',
  path: '/api/history-thumbnail/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/inspiration': typeof InspirationRoute
  '/api/download-image': typeof ApiDownloadImageRoute
  '/payment/return': typeof PaymentReturnRoute
  '/api/history-thumbnail/$id': typeof ApiHistoryThumbnailIdRoute
  '/api/xunhupay/notify': typeof ApiXunhupayNotifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/inspiration': typeof InspirationRoute
  '/api/download-image': typeof ApiDownloadImageRoute
  '/payment/return': typeof PaymentReturnRoute
  '/api/history-thumbnail/$id': typeof ApiHistoryThumbnailIdRoute
  '/api/xunhupay/notify': typeof ApiXunhupayNotifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/inspiration': typeof InspirationRoute
  '/api/download-image': typeof ApiDownloadImageRoute
  '/payment/return': typeof PaymentReturnRoute
  '/api/history-thumbnail/$id': typeof ApiHistoryThumbnailIdRoute
  '/api/xunhupay/notify': typeof ApiXunhupayNotifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/disclaimer'
    | '/inspiration'
    | '/api/download-image'
    | '/payment/return'
    | '/api/history-thumbnail/$id'
    | '/api/xunhupay/notify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disclaimer'
    | '/inspiration'
    | '/api/download-image'
    | '/payment/return'
    | '/api/history-thumbnail/$id'
    | '/api/xunhupay/notify'
  id:
    | '__root__'
    | '/'
    | '/disclaimer'
    | '/inspiration'
    | '/api/download-image'
    | '/payment/return'
    | '/api/history-thumbnail/$id'
    | '/api/xunhupay/notify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisclaimerRoute: typeof DisclaimerRoute
  InspirationRoute: typeof InspirationRoute
  ApiDownloadImageRoute: typeof ApiDownloadImageRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  ApiHistoryThumbnailIdRoute: typeof ApiHistoryThumbnailIdRoute
  ApiXunhupayNotifyRoute: typeof ApiXunhupayNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/return': {
      id: '/payment/return'
      path: '/payment/return'
      fullPath: '/payment/return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download-image': {
      id: '/api/download-image'
      path: '/api/download-image'
      fullPath: '/api/download-image'
      preLoaderRoute: typeof ApiDownloadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xunhupay/notify': {
      id: '/api/xunhupay/notify'
      path: '/api/xunhupay/notify'
      fullPath: '/api/xunhupay/notify'
      preLoaderRoute: typeof ApiXunhupayNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history-thumbnail/$id': {
      id: '/api/history-thumbnail/$id'
      path: '/api/history-thumbnail/$id'
      fullPath: '/api/history-thumbnail/$id'
      preLoaderRoute: typeof ApiHistoryThumbnailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisclaimerRoute: DisclaimerRoute,
  InspirationRoute: InspirationRoute,
  ApiDownloadImageRoute: ApiDownloadImageRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  ApiHistoryThumbnailIdRoute: ApiHistoryThumbnailIdRoute,
  ApiXunhupayNotifyRoute: ApiXunhupayNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
