/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicEzfpyNotifyRouteImport } from './routes/api/public/ezfpy-notify'

const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEzfpyNotifyRoute = ApiPublicEzfpyNotifyRouteImport.update({
  id: '/api/public/ezfpy-notify',
  path: '/api/public/ezfpy-notify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inspiration': typeof InspirationRoute
  '/api/public/ezfpy-notify': typeof ApiPublicEzfpyNotifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inspiration': typeof InspirationRoute
  '/api/public/ezfpy-notify': typeof ApiPublicEzfpyNotifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inspiration': typeof InspirationRoute
  '/api/public/ezfpy-notify': typeof ApiPublicEzfpyNotifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inspiration' | '/api/public/ezfpy-notify'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inspiration' | '/api/public/ezfpy-notify'
  id: '__root__' | '/' | '/inspiration' | '/api/public/ezfpy-notify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InspirationRoute: typeof InspirationRoute
  ApiPublicEzfpyNotifyRoute: typeof ApiPublicEzfpyNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ezfpy-notify': {
      id: '/api/public/ezfpy-notify'
      path: '/api/public/ezfpy-notify'
      fullPath: '/api/public/ezfpy-notify'
      preLoaderRoute: typeof ApiPublicEzfpyNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InspirationRoute: InspirationRoute,
  ApiPublicEzfpyNotifyRoute: ApiPublicEzfpyNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
