// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { authenticateSupabaseRequest } from '../../lib/supabase-request-auth'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next, context }) => {
    
    const request = getRequest();
    if (!request?.headers) throw new Error('Unauthorized: No request headers available');
    const { supabase, userId, claims } = await authenticateSupabaseRequest(request);

    return next({
      context: {
        ...(context && typeof context === "object" ? context : {}),
        supabase,
        userId,
        claims,
      },
    });
  },
);
